name: Build Mines-Casino

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:  # Trigger workflow on pull requests

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner with Visual Studio pre-installed

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install .NET Framework 4.6.1 Developer Pack
      - name: Install .NET Framework 4.6.1 Developer Pack
        run: |
          choco install dotnetfx --version=4.6.1 -y

      # Step 3: Build solution with MSBuild
      - name: Build solution
        run: |
          msbuild Mines-Casino.sln /p:Configuration=Release

      # Step 4: Run tests (Optional: remove if not applicable)
      - name: Run tests
        run: |
          vstest.console.exe **\*.Tests.dll --logger:trx

      # Step 5: Upload build artifacts (Optional: save compiled files for download)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '**/bin/Release/'
