name: Build Mines-Casino

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:  # Trigger on pull requests

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner with Visual Studio pre-installed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Specify the required .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Mines-Casino.sln

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build Mines-Casino.sln --configuration Release

      # Step 5: Run tests (optional, remove if not applicable)
      - name: Run tests
        run: dotnet test Mines-Casino.sln --configuration Release

      # Step 6: Save build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '**/bin/Release/'  # Upload all files in the Release directories
